backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/images"
public_folder: "/assets/images"
collections:
  - name: "podcasts"
    label: "Podcasts"
    folder: "app/content/podcasts"
    create: true
    slug: "---"
    fields:
      - { label: "title", name: "title", widget: "string" }
      - { label: "episode", name: "episode", widget: "string" }
      - { label: "date", name: "date", widget: "date", format: 'YYYY-MM-DD' }
      - { label: "acastEpisode", name: "acastEpisode", widget: "string", required: false }
      - { label: "spotifyLink", name: "spotifyLink", widget: "string", required: false }
      - { label: "googlePodcastsLink", name: "googlePodcastsLink", widget: "string", required: false }
      - { label: "applePodcastsLink", name: "applePodcastsLink", widget: "string", required: false }
      - { label: "amazonLink", name: "amazonLink", widget: "string", required: false }
      - { label: "ogImage", name: "ogImage", widget: "string", required: false }
      - { label: "permalink", name: "permalink", widget: "string", required: false }
      - { label: "intro", name: "intro", widget: "string", required: false }
      - { label: "photo", name: "photo", widget: "string", required: false }
      - label: "people"
        name: "people"
        widget: "list"
        summary: '{{fields.name}}'
        fields:
          - {label: name, name: name, widget: string}
          - {label: photo, name: photo, widget: string, required: false}
          - label: "social"
            name: "social"
            widget: "list"
            fields:
              - {label: href, name: href, widget: string, required: false}
              - {label: title, name: title, widget: string}
              - {label: type, name: type, widget: select, options: ["twitter", "website", "github", "codepen"]}

      - { label: "body", name: "body", widget: "markdown" }
